---
kind: pipeline
type: docker
name: build

steps:
- name: "test"
  image: python:3.8
  commands:
    - "git submodule update --recursive --remote --init"
    - "pip install -r requirements-docker.txt"
    - "python3 setup.py install"
    - "python3 -m unittest discover test/ --verbose"

- name: "set Docker image tags"
  image: bash
  commands:
    - "bash .drone-write-tags.sh $DRONE_TAG > .tags"
    - "# Will build the following tags:"
    - "cat .tags"

- name: "build Docker image"
  image: plugins/docker
  settings:
    repo: jlu5/pylink
    username:
      from_secret: docker_user
    password:
      from_secret: docker_token

trigger:
  event:
  - tag
  ref:
    exclude:
    - refs/tags/*alpha*
    - refs/tags/*dev*
